"""Add core foundation models

Revision ID: 0725f0b8b302
Revises: 40bce457b771
Create Date: 2026-10-03 23:00:20.371790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0725f0b8b302'
down_revision: Union[str, None] = '40bce457b771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('hazard', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_alerts_location_id'), 'active_alerts', ['location_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('tz', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('chat_sessions', sa.Column('user_role', sa.String(length=50), nullable=False, server_default='general_public'))
    op.drop_index(op.f('idx_weather_snapshots_city_timestamp'), table_name='weather_snapshots')
    op.create_index('idx_weather_snapshots_city_timestamp', 'weather_snapshots', ['city', 'timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_weather_snapshots_city_timestamp', table_name='weather_snapshots')
    op.create_index(op.f('idx_weather_snapshots_city_timestamp'), 'weather_snapshots', ['city', 'timestamp'], unique=False)
    op.drop_column('chat_sessions', 'user_role')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_active_alerts_location_id'), table_name='active_alerts')
    op.drop_table('active_alerts')
    # ### end Alembic commands ###
