"""Add provider and active alert details

Revision ID: 38661a7d3a71
Revises: 0725f0b8b302
Create Date: 2026-10-03 23:05:22.127094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38661a7d3a71'
down_revision: Union[str, None] = '0725f0b8b302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_alerts', sa.Column('city', sa.String(length=100), nullable=False, server_default='unknown'))
    op.add_column('active_alerts', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('active_alerts', sa.Column('source', sa.String(length=50), nullable=False, server_default='skycast'))
    op.add_column('active_alerts', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.alter_column('active_alerts', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('active_alerts', 'hazard',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index('idx_active_alerts_city_active', 'active_alerts', ['city', 'is_active'], unique=False)
    op.create_index('idx_active_alerts_tier', 'active_alerts', ['tier'], unique=False)
    op.create_index(op.f('ix_active_alerts_city'), 'active_alerts', ['city'], unique=False)
    op.add_column('weather_snapshots', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('weather_snapshots', sa.Column('is_stale', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_snapshots', 'is_stale')
    op.drop_column('weather_snapshots', 'provider')
    op.drop_index(op.f('ix_active_alerts_city'), table_name='active_alerts')
    op.drop_index('idx_active_alerts_tier', table_name='active_alerts')
    op.drop_index('idx_active_alerts_city_active', table_name='active_alerts')
    op.alter_column('active_alerts', 'hazard',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('active_alerts', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('active_alerts', 'is_active')
    op.drop_column('active_alerts', 'source')
    op.drop_column('active_alerts', 'description')
    op.drop_column('active_alerts', 'city')
    # ### end Alembic commands ###
